apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{appName}}
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
      metadata:
        labels:
            # Convention in SC-Pipelines
            name: {{appName}}
      spec:
        containers:
        - name: {{appName}}
          image: {{dockerOrg}}/github-webhook:{{version}}
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: SYSTEM_PROPS # additional options to be passed to the running process
            value: "{{systemProps}}"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3